### ISSUE TITLE
Github pages deploy jogosultág request

### ISSUE THREAD

**Issue by ktivadar** [Teaching-projects/SZE-MOSZE-2021-SZEMA#10]

**Comment by ktivadar** [comment]
A deploy sikerült, viszont csak az URL elérést nem tudtam beállítani hozzá, jogosultság hiányában.

**Comment by hegyhati** [comment]
Szereted generalni nekem az ertesiteseket :-D Beallitottam a gh-pages/root-ot,

**Comment by hegyhati** [comment]
(persze ki lehetett volna a felev utolso elotti napja elott is nyitni az issue-t ;-) )

**Comment by ktivadar** [comment]
Elnézést kérek az értesítések, és a késői issue miatt. És nagyon köszönöm a beállítást, így már működik! :)
