### ISSUE TITLE
Kész beadandó & Github pages URL

### ISSUE THREAD

**Issue by ktivadar** [Teaching-projects/SZE-MOSZE-2021-SZEMA#15]
Kedves @hegyhati !

Workflow-ban master branch push esetén be lett állítva az automatikus deploy a generált dokumentumokból github pages-re (gh-pages branch). Azonban az URL-t nem tudtam már beállítani, mivel nem volt jogosultságom a repo.-hoz. 

Ezen kívül elkészült a beadandó project, a videók is felkerültek hozzá a [master/videos](https://github.com/Teaching-projects/SZE-MOSZE-2021-SZEMA/tree/master/videos) mappában.

**Comment by hegyhati** [comment]
A `Report.md`-t csak en nem talalom?

**Comment by hegyhati** [comment]
Namost az osszes commit @tivadark  Toled szarmazik. A tobbiektol osszesen annyit lattam, hogy @csiszar197  leapprove-olt minden komment nelkul nehany PR-t, a tobbiektol megcsak ennyi contribution-t sem latok. 

Ez alapjan @tivadark jeles, tobbieknek nem tudom ertekelni a felevet. Ha nem vettem eszre valami commitokat, stb, pls linkeljetek. Ma meg tudok modositani a jegyeken.

**Comment by ktivadar** [comment]
Köszönöm szépen @hegyhati !

**Comment by zajovicseszter** [comment]
Kedves Tanárúr @hegyhati ! Elnézést, valamiért kimaradt a saját munkák leírása, ezt most pótoltuk. A linken eléri a report.md-t, amelyben minden megtalálható. 
https://github.com/Teaching-projects/SZE-MOSZE-2021-SZEMA/blob/report/Report.md

**Comment by hegyhati** [comment]
A Report-nak orulok, de:

Egyreszt a "tervezes" az szep dolog, de ez a targy nem errol szol. Ha valaki csak azt csinalt, meg felulet nyomkodast, akkor az nem csinalt olyat, ami a targyhoz tartozna.

Masreszt mindenkihez ide be van irva, hogy unit tesztet irt, meg dokumentaciot, meg ilyenek, de ezt csak a report-ban latom, a valosagban nem.  Githubon az latszik, hogy csak @tivadark commitolt. Illetve most mar van ott 2 commit @csiszar197 -tol, ami hajnalban meg nem volt ott:

![image](https://user-images.githubusercontent.com/13832329/123395897-fd888b80-d5a0-11eb-81a6-44f11ab55c0d.png)

Szoval kerek linkeket a commitokra, ami tenylegesen a Ti munkatok.

**Comment by hegyhati** [comment]
Itt sem latom, es a commit history-t is par oldalig visszagorgettem. 
![image](https://user-images.githubusercontent.com/13832329/123396364-83a4d200-d5a1-11eb-846b-a769965aa3a1.png)
